# Generated by Django 4.0.3 on 2022-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0003_alter_discs_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discs',
            name='diametr',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='diametr',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='load_index',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='profile',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='width',
            field=models.IntegerField(max_length=3),
        ),
    ]
