# Generated by Django 4.0.3 on 2022-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0004_alter_discs_diametr_alter_rubber_diametr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=50)),
                ('width', models.FloatField(max_length=4)),
                ('diametr', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Discs',
        ),
        migrations.AlterField(
            model_name='rubber',
            name='diametr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='load_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='profile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rubber',
            name='width',
            field=models.IntegerField(),
        ),
    ]
